### ISSUE TITLE
Error activate the plugin

### ISSUE THREAD

**Issue by INSIinc** [dutchigor/pluggable-electron-demo#3]
After I finished packaging and installing, when I click to activate the plugin, I get this error in the console.
<img width="390" alt="image" src="https://github.com/dutchigor/pluggable-electron-demo/assets/42080694/7ff2c505-6597-4a13-b07d-3e9ad66fcfed">

**Comment by ap1969** [comment]
Hi, I just found the same thing: it's looking for a .mjs file, but the file produced in /dist is .es.js

in package.json, change to the following:

"main": "dist/demo-plugin-vue.es.js",

However, even though I've done that, I'm now getting 

```
Uncaught (in promise) Error: Activation point "init" was triggered but does not exist on plugin demo-plugin
    at l (import-manager.js:52:11)
    at async p.trigger (Activation.js:29:15)
    at async Promise.all (:8080/index 0)
    at async Object.trigger (activation-manager.js:54:3)
    at async Proxy.activate (activate-plugins.vue:16:7)
```

Any ideas?

**Comment by ap1969** [comment]
Hmm. Maybe something to do with my setup - I'm trying to integrate it into an existing electron app. A clean install of this works fine.
